version: "3.8"

services:
  backend:
    build: .
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./docs:/app/docs
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
